### ISSUE TITLE
Version supports Minecraft 26.2

### ISSUE THREAD

**Issue by buku1** [stonar96/RayTraceAntiXray#56]
Version supports Minecraft 26.2

**Comment by SystemDeeeeeeeeez** [comment]
Bought just a few minutes ago, Doesn't work on 26.2 at-all. An error is also shown every once in a while

`[09:00:28 ERROR]: [RayTraceAntiXray] Unhandled exception number 2048 occurred in onPacketSending(PacketEvent) for RayTraceAntiXray
java.lang.NoSuchMethodError: 'long net.minecraft.world.level.ChunkPos.asLong(int, int)'
        at RayTraceAntiXray-1.16.3.jar//com.vanillage.raytraceantixray.listeners.PacketListener.onPacketSending(PacketListener.java:147) ~[?:?]
        at ProtocolLib.jar//com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:76) ~[?:?]
        at ProtocolLib.jar//com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:123) ~[?:?]
        at ProtocolLib.jar//com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[?:?]
        at ProtocolLib.jar//com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:123) ~[?:?]
        at ProtocolLib.jar//com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30) ~[?:?]
        at ProtocolLib.jar//com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:102) ~[?:?]
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:539) ~[?:?]
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:514) ~[?:?]
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:529) ~[?:?]
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:46) ~[?:?]
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:235) ~[?:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:486) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.network.Connection$PacketSendAction.lambda$new$0(Connection.java:1059) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.network.Connection$WrappedConsumer.accept(Connection.java:1043) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.network.Connection.processQueue(Connection.java:584) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.network.Connection.flushQueue(Connection.java:541) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.network.Connection.send(Connection.java:466) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:396) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:358) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.sendUnloadChunkRaw(RegionizedPlayerChunkLoader.java:461) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.sendUnloadChunk(RegionizedPlayerChunkLoader.java:452) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader$PlayerChunkLoaderData$1.removeCallback(RegionizedPlayerChunkLoader.java:477) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader$PlayerChunkLoaderData$1.removeCallback(RegionizedPlayerChunkLoader.java:469) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at ca.spottedleaf.moonrise.common.misc.SingleUserAreaMap.update(SingleUserAreaMap.java:210) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.update(RegionizedPlayerChunkLoader.java:965) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader.updatePlayer(RegionizedPlayerChunkLoader.java:206) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at ca.spottedleaf.moonrise.paper.util.BaseChunkSystemHooks.updateMaps(BaseChunkSystemHooks.java:168) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.server.level.ChunkMap.move(ChunkMap.java:935) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.server.level.ServerChunkCache.move(ServerChunkCache.java:722) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1777) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:70) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:145) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.network.PacketProcessor$ListenerAndPacket.handle(PacketProcessor.java:84) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.network.PacketProcessor.executeSinglePacket(PacketProcessor.java:39) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at net.minecraft.server.dedicated.DedicatedServer.tickServer(DedicatedServer.java:420) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:615) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:604) ~[canvas-26.2.jar:26.2-861-17f40c8]
        at ca.spottedleaf.concurrentutil.scheduler.EDFSchedulerThreadPool$TickThreadRunner.run(EDFSchedulerThreadPool.java:528) ~[leafpile-1.0.0.jar:26.2-861-17f40c8]
        at ca.spottedleaf.concurrentutil.util.LazyRunnable.run(LazyRunnable.java:25) ~[leafpile-1.0.0.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1516) ~[?:?]
`

**Comment by stonar96** [comment]
> Bought just a few minutes ago, Doesn't work on 26.2 at-all.

@SystemDeeeeeeeeez Thanks and sorry for the inconvenience. I'm aware that the plugin hasn't been updated yet. However, the plugin page displays the supported version(s) in four different places. You could have read that before buying it. Your review is therefore invalid.
